//! Command implementations.

pub mod calc;
pub mod chat;
pub mod config;
#[cfg(feature = "egui")]
pub mod egui;
pub mod encode;
pub mod env;
pub mod expr;
pub mod fun;
pub mod grep;
pub mod hash;
pub mod http;
pub mod json;
pub mod net;
pub mod rand;
pub mod system;
pub mod text;
pub mod time;
#[cfg(feature = "ui")]
pub mod ui;
pub mod uuid;
pub mod watch;
